# Generated by Django 5.1.6 on 2025-02-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employess', to='relationship_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.ManyToManyField(db_column='department', related_name='products', to='relationship_app.department')),
            ],
        ),
    ]
