# Generated by Django 5.1.6 on 2025-02-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_delete_product'),
    ]

    
